# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@1.3.0
jobs:
  build_backend:
    description: build and push to aws
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --checkout
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY  
          aws-region: AWS_REGION
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          create-repo: false
          dockerfile: Dockerfile
          path: ./backend/.
          profile-name: default
          repo: 'la-backend'
          region: AWS_REGION
          tag: '${CIRCLE_SHA1},latest'
      # - aws-ecs/update-service:
      #     family: '<< parameters.env_env >>-kde20-api'
      #     cluster-name: 'KDE-<< parameters.env_env >>'
      #     service-name: 'srv-kde20-api'
      #     # skip-task-definition-registration: true
      #     container-image-name-updates: 'container=kde20-api,tag=${CIRCLE_SHA1},image=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com'
workflows: # testing
  build_and_push:
    jobs:
      - build_backend:
          name: 'build_backend'